name: Build Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push the Docker image
      working-directory: ${{ matrix.images }}
      run: |
        docker build -t shinhwagk/mysql_query:latest .
        docker push shinhwagk/mysql_query:latest